development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 154390471577-abf1217i066nnsv987q03o994rggsgb7.apps.googleusercontent.com
  google_client_secret: WTNWVGaHUuw7XiYafhFZE5UE
